[package]
name = "slang"
version = "0.1.0"
authors = ["Daniel Solarte <danielsolartech@hotmail.com>"]
edition = "2018"

[[bin]]
name = "slang"
path = "main.rs"

[dependencies]
clap = "3.0.0-beta.2"
semver = { version = "0.10", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
slang-compiler = { path = "../compiler", version = "0.1.0" }
slang-parser = { path = "../parser", version = "0.1.0" }
