[package]
name = "slang-compiler"
version = "0.1.0"
authors = ["Daniel Solarte <danielsolartech@hotmail.com>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
slang-parser = { path = "../parser", version = "0.1.0" }
