[package]
name = "sflynlang-compiler"
version = "0.1.0"
authors = ["Sflynlang <sflynlang@outlook.com>"]
edition = "2018"
repository = "https://github.com/sflynlang/sflynlang-compiler"

[lib]
path = "lib.rs"

[dependencies]
sflynlang-parser = { path = "../parser", version = "0.1.0" }
