name: Rust CI

on: [push, pull_request]

jobs:
  cargo-publish:
    name: Publish Cargo Package
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Publish
        run: |
          cd compiler
          cargo publish
          sleep 20
          cd ../parser
          cargo publish
          sleep 20
          cd ../core
          cargo publish

  build-release:
    name: Build Release (${{ matrix.target }})
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: wondwise-x86_64-unknown-linux-gnu.zip

          - target: x86_64-apple-darwin
            os: macOS-latest
            name: wondwise-x86_64-apple-darwin.zip

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: wondwise-x86_64-pc-windows-msvc.zip

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Cargo Packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.target }}

      - name: Pre-release (build)
        uses: actions-rs/cargo@v1
        env:
          SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
        with:
          command: build
          args: --release --workspace --target ${{ matrix.target }}
          use-cross: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Pre-release (windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          strip wondwise.exe
          7z a ../../../${{ matrix.name }} wondwise.exe
          cd -

      - name: Pre-release (linux & macos)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          strip wondwise || true
          zip -9r ../../../${{ matrix.name }} wondwise
          cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}


  github-release:
    name: Publish Github Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build-release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Artifacts
        uses: actions/download-artifact@v2

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: wondwise-*/wondwise-*
          body_path: CHANGELOG.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
